# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-11 14:50
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='assignees_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('assigneed_to', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='comments_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('comment', models.CharField(max_length=150)),
                ('commented_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='tasks_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('deadline', models.DateTimeField(default=datetime.datetime.now)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('state', models.CharField(choices=[('todo', 'To-Do'), ('inprogress', 'In-Progress'), ('needhelp', 'Need-Help'), ('review', 'Review'), ('improvements', 'Improvements'), ('closed', 'Closed')], default='todo', max_length=20)),
                ('type', models.CharField(choices=[('MainTask', 'Main-Task'), ('EpicTask', 'Epic-Task'), ('GeneralTask', 'General-Task'), ('SubTask', 'Sub-Task'), ('MiniTask', 'Mini-Task')], default=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='getagrip_app.tasks_log'), max_length=20)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('maintask', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='getagrip_app.tasks_log')),
            ],
        ),
        migrations.AddField(
            model_name='comments_log',
            name='task',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='getagrip_app.tasks_log'),
        ),
        migrations.AddField(
            model_name='assignees_log',
            name='task',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='getagrip_app.tasks_log'),
        ),
    ]
